
---
    apiVersion: apiextensions.k8s.io/v1beta1
    kind: CustomResourceDefinition
    metadata:
      name: workflow.cncf.io
    spec:
      names:
        kind: Workflow
        listKind: WorkflowList
        plural: workflows
        shortNames:
        - wf
        singular: workflow
      scope: Namespaced
      subresources:
        status: {}
      validation:
        openAPIV3Schema:
          description: Workflow is the Schema for the workflow definitions API
          properties:
            apiVersion:
              description: 'APIVersion defines the versioned schema of this representation
                of an object. Servers should convert recognized schemas to the latest
                internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
              type: string
            kind:
              description: 'Kind is a string value representing the REST resource this
                object represents. Servers may infer this from the endpoint the client
                submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
              type: string
            metadata:
              type: object
            spec:
              description: WorkflowSpec defines the desired state of a Workflow
              properties:
                workflowDefinition:
                  description: "Workflow Definition content or reference to the actual definition"
                  type: string
              type: object
            status:
              description: WorkflowStatus defines the observed state of a Workflow
              properties:
                deployed:
                  description: "Specifies if the Workflow has been deployed and ready to be instantiated"
                  type: boolean
                latestVersion:
                  description: "Specifies the latest version of a Workflow Definition available for this type"  
                  type: string
              required:
              - deployed
              - latestVersion
              type: object
          type: object
      version: v1
      versions:
      - name: v1
        served: true
        storage: true
    status:
      acceptedNames:
        kind: ""
        plural: ""
      conditions: []
      storedVersions: []
    